CREATE TABLE Question(
Id INT PRIMARY KEY IDENTITY(1,1),
Title NVARCHAR(MAX),
[Description] NVARCHAR(MAX),
CategoryId INT FOREIGN KEY REFERENCES Category(Id),
UserId NVARCHAR(450) FOREIGN KEY REFERENCES AspNetUsers(Id),
UpVotes NVARCHAR(MAX),
Views INT,
CreatedOn DATETIME NULL);